name: .NET Format Linter

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  dotnet-format-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x' 

      - name: Install dotnet format tool
        run: dotnet tool install --global dotnet-format

      - name: Add .NET tools to PATH
        run: echo "::add-path::$(dotnet --list-tools | grep 'dotnet-format' | cut -d ' ' -f2)"

      - name: Run dotnet format
        run: dotnet format --check

      - name: Fail on unformatted code
        if: failure()
        run: echo "Code formatting issues found. Please run 'dotnet format' locally and commit the changes."