name: CI build

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8' 

      - name: Install dotnet format
        run: dotnet tool install --global dotnet-format

      - name: Setup PATH for .NET tools
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Run dotnet format
        run: dotnet format EC-Billing/EC-Billing.csproj --verify-no-changes --verbosity diagnostic > format-output.log

      - name: Run dotnet format on solution (.sln)
        run: dotnet format demo.sln --verify-no-changes --verbosity diagnostic > format-output-sln.log 


      - name: Fail on unformatted code
        if: failure()
        run: 
          if [[ -s format-output.log ]]; then
            echo "Code formatting issues found in EC-Billing.csproj:"
            cat format-output.log
            echo "Formatting errors detected in EC-Billing.csproj."
          
          if [[ -s format-output-sln.log ]]; then
            echo "Code formatting issues found in demo.sln:"
            cat format-output-sln.log
            echo "Formatting errors detected in demo.sln."

          if [[ -s format-output.log || -s format-output-sln.log ]]; then
            echo "Please run 'dotnet format' locally and commit the changes."
            exit 1

