name: .NET Format Linter

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  dotnet-format-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8'

      - name: Install dotnet format
        run: dotnet tool install --global dotnet-format

      - name: Setup PATH for .NET tools
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Run dotnet format
        id: format-check
        run: |
          dotnet format EC-Billing/EC-Billing.csproj --verify-no-changes || echo "Formatting issues detected"
        continue-on-error: true

      - name: Show formatting issues
        if: steps.format-check.outcome == 'failure'
        run: |
          echo "Formatting issues found! Please run 'dotnet format' locally to fix them."
          dotnet format EC-Billing/EC-Billing.csproj
          
      - name: Fail on unformatted code
        if: steps.format-check.outcome == 'failure'
        run: exit 1

      - name: Restore Dependencies
        run: dotnet restore EC-Billing/EC-Billing.csproj

      - name: Build Solution
        run: dotnet build EC-Billing/EC-Billing.csproj --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test EC-Billing/EC-Billing.csproj --no-restore --logger "console;verbosity=detailed"
