name: Run EF Core Migrations

on:
  workflow_dispatch: 

jobs:
  check-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Verify Secret Existence
        env:
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
        run: echo $DB_CONNECTION_STRING >> secrets.txt