name: DB_CON_SECRETS

on:
  workflow_dispatch:  # Allows manual run for testing

jobs:
  check-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Verify Secret Existence
        env:
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
        run: |
          if [ -z "$DB_CONNECTION_STRING" ]; then
            echo "DB_CONNECTION_STRING is not set."
          else
            echo "DB_CONNECTION_STRING is set correctly."
          fi
